version: "3.8"
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: [ "node", "index.js" ]
